package view;

import connection.Connect;
import controlador.controlador;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 *@author Julian Esteban Bonolis Urrego NRC 1991 /// me base mucho el la profundizacion del reto 4 ya que realmente vi muy poco con la conexion a base de data , feliz dia .
 */
public class JframeReto4 extends javax.swing.JFrame {
    
   controlador conntrol = new controlador();
   
     public JframeReto4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelreto4 = new javax.swing.JTabbedPane();
        IngresarPanel = new javax.swing.JPanel();
        labelnombre = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        MunicipioLabel = new javax.swing.JLabel();
        Nombretxtf = new javax.swing.JTextField();
        idtxtf = new javax.swing.JTextField();
        municipiotxtf = new javax.swing.JTextField();
        label_cuerpo_de_agua = new javax.swing.JLabel();
        labeltipodeagua = new javax.swing.JLabel();
        labelirca = new javax.swing.JLabel();
        ingresarButton = new javax.swing.JButton();
        Tipo_de_cuerpo_aguatxtf = new javax.swing.JTextField();
        Tipo_de_aguatxtf = new javax.swing.JTextField();
        Ircatxtf = new javax.swing.JTextField();
        ProcesarPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        obtenerdatosTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        procesardatosArea = new javax.swing.JTextArea();
        obtenerdatosButton = new javax.swing.JButton();
        procesarButton = new javax.swing.JButton();
        EditarPanel = new javax.swing.JPanel();
        Idlabel = new javax.swing.JLabel();
        Idtxtf = new javax.swing.JTextField();
        BuscarButton = new javax.swing.JButton();
        ResultadodebusqueaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nombrebtxtf = new javax.swing.JTextField();
        Idbtxtf = new javax.swing.JTextField();
        Municipiobtxtf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tipo_cuerop_aguabtxtf = new javax.swing.JTextField();
        Tipo_de_aguabtxtf = new javax.swing.JTextField();
        Ircabtxtf = new javax.swing.JTextField();
        EditarbButton = new javax.swing.JButton();
        EliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LECTOR CALIDAD AGUA");
        setResizable(false);

        labelnombre.setText("Nombre");

        idLabel.setText("id");

        MunicipioLabel.setText("Municipio");

        label_cuerpo_de_agua.setText("Tipo de cuerpo de agua");

        labeltipodeagua.setText("Tipo de agua");

        labelirca.setText("Irca");

        ingresarButton.setText("Ingresar");
        ingresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IngresarPanelLayout = new javax.swing.GroupLayout(IngresarPanel);
        IngresarPanel.setLayout(IngresarPanelLayout);
        IngresarPanelLayout.setHorizontalGroup(
            IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresarPanelLayout.createSequentialGroup()
                        .addGroup(IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombretxtf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_cuerpo_de_agua, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tipo_de_cuerpo_aguatxtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtf)
                            .addComponent(labeltipodeagua)
                            .addComponent(Tipo_de_aguatxtf, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MunicipioLabel)
                            .addComponent(municipiotxtf)
                            .addComponent(labelirca, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ircatxtf, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                    .addComponent(ingresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        IngresarPanelLayout.setVerticalGroup(
            IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnombre)
                    .addComponent(idLabel)
                    .addComponent(MunicipioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombretxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipiotxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cuerpo_de_agua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltipodeagua)
                    .addComponent(labelirca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo_de_cuerpo_aguatxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tipo_de_aguatxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ircatxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(ingresarButton)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        panelreto4.addTab("Ingresar", IngresarPanel);

        obtenerdatosTextArea.setEditable(false);
        obtenerdatosTextArea.setColumns(20);
        obtenerdatosTextArea.setRows(5);
        jScrollPane1.setViewportView(obtenerdatosTextArea);

        procesardatosArea.setEditable(false);
        procesardatosArea.setColumns(20);
        procesardatosArea.setRows(5);
        jScrollPane2.setViewportView(procesardatosArea);

        obtenerdatosButton.setText("Obtener datos");
        obtenerdatosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerdatosButtonActionPerformed(evt);
            }
        });

        procesarButton.setText("procesar datos");
        procesarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProcesarPanelLayout = new javax.swing.GroupLayout(ProcesarPanel);
        ProcesarPanel.setLayout(ProcesarPanelLayout);
        ProcesarPanelLayout.setHorizontalGroup(
            ProcesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcesarPanelLayout.createSequentialGroup()
                .addGroup(ProcesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProcesarPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProcesarPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(ProcesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(obtenerdatosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(procesarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        ProcesarPanelLayout.setVerticalGroup(
            ProcesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcesarPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ProcesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(obtenerdatosButton)
                .addGap(27, 27, 27)
                .addComponent(procesarButton)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        panelreto4.addTab("Procesar datos", ProcesarPanel);

        Idlabel.setText("id");

        BuscarButton.setText("Buscar");
        BuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonActionPerformed(evt);
            }
        });

        ResultadodebusqueaLabel.setText("Resultado de busqueda");

        jLabel1.setText("Nombre");

        jLabel2.setText("Id");

        jLabel3.setText("Municipio");

        Nombrebtxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrebtxtfActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de cuerpo de agua");

        jLabel5.setText("Tipo de agua");

        jLabel6.setText("Irca");

        EditarbButton.setText("Editar");
        EditarbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarbButtonActionPerformed(evt);
            }
        });

        EliminarButton.setText("Eliminar");
        EliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditarPanelLayout = new javax.swing.GroupLayout(EditarPanel);
        EditarPanel.setLayout(EditarPanelLayout);
        EditarPanelLayout.setHorizontalGroup(
            EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultadodebusqueaLabel)
                    .addGroup(EditarPanelLayout.createSequentialGroup()
                        .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditarPanelLayout.createSequentialGroup()
                                .addComponent(Idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(Idtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(EditarPanelLayout.createSequentialGroup()
                                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombrebtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(Idbtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EditarPanelLayout.createSequentialGroup()
                                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Tipo_cuerop_aguabtxtf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(Tipo_de_aguabtxtf))))
                        .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BuscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditarPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Municipiobtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditarPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ircabtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(EditarPanelLayout.createSequentialGroup()
                        .addComponent(EditarbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarButton)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        EditarPanelLayout.setVerticalGroup(
            EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idlabel)
                    .addComponent(Idtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResultadodebusqueaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombrebtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Idbtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Municipiobtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo_cuerop_aguabtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tipo_de_aguabtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ircabtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(EditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarbButton)
                    .addComponent(EliminarButton))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        panelreto4.addTab("Ediatar/Eliminar", EditarPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(panelreto4, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelreto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerdatosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerdatosButtonActionPerformed
    
        
        String query = "SELECT * from datos";
        obtenerdatosTextArea.setEditable(false);
        try (Connection conn = Connect.Connet(); Statement stmt = conn.createStatement()) {
            ResultSet resultSet = stmt.executeQuery(query);
            ResultSetMetaData rsmd = resultSet.getMetaData();
            int columnsNumber = rsmd.getColumnCount();
            String products = "";
            while (resultSet.next()) {
                for (int i = 1; i <= columnsNumber; i++) {
                    String columnValue = resultSet.getString(i);
                    products = products + rsmd.getColumnName(i) + ":" + " " + columnValue + "\n";
                }
               obtenerdatosTextArea.setText(products);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
      
        delete();
    }//GEN-LAST:event_obtenerdatosButtonActionPerformed

    private void ingresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarButtonActionPerformed
       String nombre = Nombretxtf.getText();
       int id = Integer.parseInt(idtxtf.getText());
       String municipio = municipiotxtf.getText();
       String cuerpo = Tipo_de_cuerpo_aguatxtf.getText(); // capturo los valores en la vista
       String tipoCuerpo = Tipo_de_aguatxtf.getText();
       float Irca = Float.valueOf(Ircatxtf.getText());
       
       
       controlador.cuerpo_DeAgua(nombre, id, municipio, cuerpo,tipoCuerpo,Irca); // en el controlador esta la conecino y la sentencia para agregar la info a la bd 
       delete(); // para borrar los campos ingresados
       
    }//GEN-LAST:event_ingresarButtonActionPerformed

    private void procesarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarButtonActionPerformed
       procesardatosArea.setText(""); // limpio el area text para que no se repitna los datos
        
        try {
            conntrol.llenarArray(); // llamamos la funcion llenararray para que se llene el array con los objetos y podemos hacer las validaciones 
            procesardatosArea.append(conntrol.NivelesCuerpos()); // gracias a que capturamos los datos en un array hacemos las validaciones 
            procesardatosArea.append(conntrol.totalmedios());     // en metodos 
            procesardatosArea.append(conntrol.nombresmedios());
            procesardatosArea.append(conntrol.menormedio());
            
        } catch (SQLException ex) {
            Logger.getLogger(JframeReto4.class.getName()).log(Level.SEVERE, null, ex);
        }
    
     
        // procesardatosArea.append("hiiiiiiiiii");
    }//GEN-LAST:event_procesarButtonActionPerformed

    private void BuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonActionPerformed
       int  idd =Integer.parseInt(Idtxtf.getText()); // capturamos la informacion de la vista buscar
            //conntrol.obtenerdatos(id);
           String[] campos = conntrol.obtenerdatos(idd); 
           
           Nombrebtxtf.setText(campos[1]);
           Idbtxtf.setText(campos[0]);
           Municipiobtxtf.setText(campos[2]);
           Tipo_cuerop_aguabtxtf.setText(campos[3]);
           Tipo_de_aguabtxtf.setText(campos[4]);
           Ircabtxtf.setText(campos[5]);
           
         
    }//GEN-LAST:event_BuscarButtonActionPerformed

    private void NombrebtxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrebtxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrebtxtfActionPerformed

    private void EliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarButtonActionPerformed
       
        int id = Integer.parseInt(Idtxtf.getText());
        conntrol.eliminardatos(id);
       JOptionPane.showMessageDialog(null, "Cuerpo de agua eliminado", "Edicion", JOptionPane.PLAIN_MESSAGE);
         delete2();
        
    }//GEN-LAST:event_EliminarButtonActionPerformed

    private void EditarbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarbButtonActionPerformed
        int numero = Integer.parseInt(Idbtxtf.getText());
        String nombre = Nombrebtxtf.getText();
        String municipio = Municipiobtxtf.getText();
        String tipoCuerpo = Tipo_cuerop_aguabtxtf.getText();
        String tipoAgua = Tipo_de_aguabtxtf.getText();
        float IRCA = Float.parseFloat(Ircabtxtf.getText());
        
        conntrol.actualizarCuerpo(nombre, numero, municipio, IRCA, tipoCuerpo, tipoAgua);
            
        JOptionPane.showMessageDialog(null, "Cuerpo de agua editado", "Edicion", JOptionPane.PLAIN_MESSAGE);
        
        
    }//GEN-LAST:event_EditarbButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeReto4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarButton;
    private javax.swing.JPanel EditarPanel;
    private javax.swing.JButton EditarbButton;
    private javax.swing.JButton EliminarButton;
    private javax.swing.JTextField Idbtxtf;
    private javax.swing.JLabel Idlabel;
    private javax.swing.JTextField Idtxtf;
    private javax.swing.JPanel IngresarPanel;
    private javax.swing.JTextField Ircabtxtf;
    private javax.swing.JTextField Ircatxtf;
    private javax.swing.JLabel MunicipioLabel;
    private javax.swing.JTextField Municipiobtxtf;
    private javax.swing.JTextField Nombrebtxtf;
    private javax.swing.JTextField Nombretxtf;
    private javax.swing.JPanel ProcesarPanel;
    private javax.swing.JLabel ResultadodebusqueaLabel;
    private javax.swing.JTextField Tipo_cuerop_aguabtxtf;
    private javax.swing.JTextField Tipo_de_aguabtxtf;
    private javax.swing.JTextField Tipo_de_aguatxtf;
    private javax.swing.JTextField Tipo_de_cuerpo_aguatxtf;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idtxtf;
    private javax.swing.JButton ingresarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_cuerpo_de_agua;
    private javax.swing.JLabel labelirca;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JLabel labeltipodeagua;
    private javax.swing.JTextField municipiotxtf;
    private javax.swing.JButton obtenerdatosButton;
    private javax.swing.JTextArea obtenerdatosTextArea;
    private javax.swing.JTabbedPane panelreto4;
    private javax.swing.JButton procesarButton;
    private javax.swing.JTextArea procesardatosArea;
    // End of variables declaration//GEN-END:variables

private void delete(){ 
    Nombretxtf.setText("");
    idtxtf.setText("");
    municipiotxtf.setText("");
    Tipo_de_cuerpo_aguatxtf.setText("");
    Tipo_de_aguatxtf.setText("");
    Ircatxtf.setText("");

}

private void delete2(){
    Idtxtf.setText("");
    Nombrebtxtf.setText("");
    Idbtxtf.setText("");
    Municipiobtxtf.setText("");
    Tipo_cuerop_aguabtxtf.setText("");
    Tipo_de_aguabtxtf.setText("");
    Ircabtxtf.setText("");

}
   
}


